[package]
name = "chess_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
actix = "0.13"
tokio = "1.45.0"
actix-web-actors = "4.3.1"
env_logger = "0.11.8"
serde = { version = "1.0", features = ["derive"] }
